version: 2.1

executors:
  terraform:
    docker:
      - image: cimg/deploy:2023.05
  node:
    docker:
      - image: cimg/node:current

  python:
    docker:
      - image: cimg/python:3.11.3
  

jobs:
  terraform_check:
    executor: terraform
    steps:
      - checkout
      - run:
          step_name: Run Terraform Validate
          command: |
            terraform init -backend=false
            terraform validate
      # - run_shell:
      #     step_name: Generate Terraform Docs
      #   .... <check terraform docs generation> ....

  msg_check:
    executor: python
    steps:
      - checkout
      - run:
          command: |
            if [ -z "${CIRCLE_PR_NUMBER}" ]; then
              MSG="`git log -n 1 --pretty=%s`"
            else
              MSG="`curl -s https://api.github.com/repos/${CIRCLE_PR_REPONAME}/pulls/${CIRCLE_PR_NUMBER}|jq .title`"
              MSG="${${MSG%%\"}##\"}"
              if [ -z "$MSG" ]; then
                MSG="`git log -n 1 --pretty=%s`"
              fi
            fi
            echo Message:$MSG
            echo PR REPO:$CIRCLE_PR_REPONAME
            hooks/commit-msg.py "$MSG"

  release:
    executor: node
    steps:
        - checkout
        - run:
            step_name: Semantic Release
            command: npx semantic-release


workflows:
  pr_test:
    jobs:
      - terraform_check
      - msg_check
  backend-test:
    when: 
      condition:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - release

  # create-a-deployment: #move this into the first step
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
      
  #     - run:
  #         command: >
  #           gh api /repos/:owner/:repo/deployments --preview ant-man --input - \

  #           --jq '"export GH_DEPLOYMENT_STATUS_URL=\(.statuses_url)"' >>
  #           $BASH_ENV \<<JSON || true

  #           {

  #           "ref": "${CIRCLE_TAG:-$CIRCLE_SHA1}",

  #           "environment": "${AWS_ENVIRONMENT,,}",

  #           "auto_merge": false,

  #           "required_contexts": []

  #           }

  
